name: bmier
description: "A Body Mass Index(BMI) Calculator"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8       # iOS Icons
  shared_preferences: ^2.3.2    # Local Storage
  google_fonts: ^6.2.1          # Custom Fonts
  google_mobile_ads: ^5.2.0     # Google Ads
  giff_dialog: ^1.0.1           # Gif Dialog


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

